name: Test - E2E

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    env:
      NODE_VER: 14.17.6
      DAPR_INSTALL_URL: https://raw.githubusercontent.com/dapr/cli/master/install/install.sh
    services:
      emqx:
        image: emqx/emqx
        ports:
          - 1883:1883 
          - 8081:8081 
          - 8083:8083 
          - 8883:8883 
          # - 8084:8084 // this port is already used?
          - 18083:18083
    steps:
    - uses: actions/checkout@v2

    # Setup .npmrc file to publish to npm
    # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
    - name: NodeJS - Install
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VER }}
        registry-url: 'https://registry.npmjs.org'

    - name: Dapr - Install CLI
      run: wget -q ${{ env.DAPR_INSTALL_URL }} -O - | /bin/bash -s ${{ env.DAPR_CLI_VER }}

    - name: Dapr - Initialize
      run: dapr init

    - name: Install Dependencies
      run: npm i
    
    - run: npm run test:unit:main
    - run: npm run test:unit:actors

    # We need to do the following assertions as dapr run doesn't fail even if the underlying app exits with error.
    # This ensures the workflow fails if any of the test fails, with error in logs.
    # The grep command looks for the text "== APP == npm ERR!" text in the log. If found exits the step with code 1.
    # This will fail the step.
    - name: run grpc tests      
      run: |
        npm run test:e2e:grpc:main | tee test_grpc_out.txt &&
        if grep "== APP == npm ERR!" -i test_grpc_out.txt -q; then
           exit 1;
        else
           echo "No error found: All tests passed";
        fi              
    
    - name: run http tests      
      run: |
        npm run test:e2e:http:main | tee test_http_out.txt
        if grep "== APP == npm ERR!" -i test_http_out.txt -q; then
           exit 1;
        else
           echo "No error found: All tests passed";
        fi
    
    - name: run actors tests       
      run: |
        npm run test:e2e:http:actors | tee test_http_actors_out.txt
        if grep "== APP == npm ERR!" -i test_http_actors_out.txt -q; then
           exit 1;
        else
           echo "No error found: All tests passed";
        fi
